I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Endings.rpy", line 776, in script
    play sound Fire
  File "renpy/common/000statements.rpy", line 300, in execute_play_sound
    renpy.sound.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "game/Endings.rpy", line 776, in <module>
    play sound Fire
NameError: name 'Fire' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Endings.rpy", line 776, in script
    play sound Fire
  File "renpy/ast.py", line 1969, in execute
    self.call("execute")
  File "renpy/ast.py", line 1957, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 300, in execute_play_sound
    renpy.sound.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/Endings.rpy", line 776, in <module>
    play sound Fire
NameError: name 'Fire' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.3.1414
 
Sat Apr 24 15:26:26 2021
