I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Endings.rpy", line 104, in script
    $inventory.add(Dagger)
  File "game/Endings.rpy", line 104, in <module>
    $inventory.add(Dagger)
NameError: name 'Dagger' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Endings.rpy", line 104, in script
    $inventory.add(Dagger)
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/Endings.rpy", line 104, in <module>
    $inventory.add(Dagger)
NameError: name 'Dagger' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.3.1414
 
Thu Apr 22 14:58:56 2021
